### ISSUE TITLE
Example is incomplete

### ISSUE THREAD

**Issue by ProxyProdigy** [cvra/goap-cpp#2]
If you compile and run example.cpp as-is, it will say "Could not find a plan!" That's because the example is incomplete, but it's a simple fix.

Before calling planner.plan in main, you need to set the initial state of both the axe and wood.

```
...

state.has_axe = false;
state.has_wood = false;

auto len = planner.plan(state, goal, actions.data(), actions.size(), path, max_path_len);

...
```

When running the example after that, you will see:

Grabbing my axe!
Cutting wood!

**Comment by AchimTuran** [comment]
I would not say the example is incomplete. The issue is that most state variables are not correctly setup during initialization phase. But @ProxyProdigy you're right, correctly setting an initial value will result in a successfully running example across most C++ compilers.

I did a similar fix for Visual Studio. Additionally, I assume the example will run fine with a release build as most compilers initialize the bool variables with false.

**Comment by antoinealb** [comment]
Thanks for the pointer. I added a clean init of the state: https://github.com/cvra/goap-cpp/commit/bc6d43d199adde3df055faef6a543fc6c9b5c215
